package ru.ls.qa.school.addressbok.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbok.model.GroupData;

public class GroupCreationTests extends TestBase {


    @Test
    public void newTest() {
        pageManager.getContactsPage().openGroupPage();
        pageManager.getGroupsListPage().initGroupCreation();
        pageManager.getGroupPage().editForm(new GroupData("test1", "test2", "test3"));
        pageManager.getGroupPage().submitCreation();
        pageManager.getGroupPage().returnToGroups();
    }

}
