package ru.ls.qa.school.addressbok.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.ls.qa.school.addressbok.appmanager.GroupHelper;
import ru.ls.qa.school.addressbok.appmanager.NavigationHelper;
import ru.ls.qa.school.addressbok.model.GroupData;

public class GroupCreationTests extends TestBase{


    @Test
    public void newTest() {
        NavigationHelper.gotoGroupPage();
        GroupHelper.initGroupCreation();
        GroupHelper.fillGroupForm(new GroupData("test1", "test2", "test3"));
        GroupHelper.submitGroupCreation();
        GroupHelper.returnToGroupPage();


    }

}
