package ru.ls.qa.school.addressbok;// Generated by Selenium IDE

import com.codeborne.selenide.Selenide;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import static com.codeborne.selenide.Selenide.$;

public class GroupCreationTests {


    @BeforeAll
    static void openPage() {
        Selenide.open("http://localhost/addressbook");
    }

    @AfterAll
    static void closeWindow() {
        Selenide.closeWebDriver();
    }

    @Test
    public void newTest() {
        $(By.name("user")).setValue("admin");
        $(By.name("pass")).setValue("secret");
        $("#LoginForm > input[type=submit]:nth-child(7)").click();
        $("#nav > ul > li.admin > a").click();
        $("#content > form > input[type=submit]:nth-child(1)").click();
        $(By.name("group_name")).setValue("test1");
        $(By.name("group_header")).setValue("test2");
        $(By.name("group_footer")).setValue("test3");
        $("#content > form > input[type=submit]:nth-child(11)").click();
        $("#content > div > i > a").click();
        $("#top > form > a").click();
    }
}
