package ru.ls.qa.school.addressbok;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;

public class GroupCreationTests extends TestBase{


    @Test
    public void newTest() {
        gotoGroupPage();
        initGroupCreation();
        fillGroupForm(new GroupData("test1", "test2", "test3"));
        submitGroupCreation();
        returnToGroupPage();


    }

}
